import React, { useState, useEffect } from "react";
import { Address, AddressInput, Contract, Meta } from "../components";
import { List, Card, Button } from "antd";
import { useContractReader } from "eth-hooks";
import { useEventListener } from "eth-hooks/events";
import { Web3Consumer } from "../helpers/Web3Context";
import Head from "next/head";
import Icon from "../assets/icon.svg";
import Gitcoin from "../assets/gitcoin.svg";
import Github from "../assets/github.svg";

function Home({ web3 }) {
  return (
    <div className="flex min-h-screen justify-center items-center">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <div className="max-w-xs rounded overflow-hidden shadow-lg my-2">
        <div className="px-6 py-4">
          <div className="font-bold text-xl mb-2">Next + Tailwind ❤️</div>
          <p className="text-grey-darker text-base">
            Next and Tailwind CSS are a match made in heaven, check out this article on how you can combine these two
            for your next app.
          </p>
        </div>
      </div>
    </div>
  );
}

export default Web3Consumer(Home);
